# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/RNAfold',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/RNAfold',
                'lib_path': 'RNAfold'},
  'syms': {'RNAfold.core': {'RNAfold.core.foo': ('core.html#foo', 'RNAfold/core.py')}}}
